@authenticated
Feature: add user

  Scenario: add a new user
    When I visit "/users"
     And I follow "Add User"
     And I fill in "name" with "chuck"
     And I fill in "password" with "norris"
     And I fill in "password_confirmation" with "norris"
     And I press "Create"
    When I visit "/users"
    Then I should see "chuck"
  
  Scenario: faulty input
    When I visit "/users"
     And I follow "Add User"
     And I fill in "name" with " "
     And I fill in "password" with "norris"
     And I fill in "password_confirmation" with "norris"
     And I press "Create"
    Then I should see "Incorrect input, please revise."
    When I follow "Add User"
     And I fill in "name" with ""
     And I fill in "password" with "norris"
     And I fill in "password_confirmation" with "norris"
     And I press "Create"
    Then I should see "Incorrect input, please revise."
    When I follow "Add User"
     And I fill in "name" with "chuck"
     And I fill in "password" with ""
     And I fill in "password_confirmation" with ""
     And I press "Create"
    Then I should see "Incorrect input, please revise."
    When I follow "Add User"
     And I fill in "name" with "chuck"
     And I fill in "password" with "nor"
     And I fill in "password_confirmation" with "ris"
     And I press "Create"
    Then I should see "Incorrect input, please revise."
    When I follow "Add User"
     And I fill in "name" with "chuck"
     And I fill in "password" with "12345"
     And I fill in "password_confirmation" with "12345"
     And I press "Create"
    Then I should see "Incorrect input, please revise."
    When I visit "/users"
    Then I should not see "chuck"
  
  Scenario: trying to add an existing user
    Given a user "chuck/norris"
    When I visit "/users"
     And I follow "Add User"
     And I fill in "name" with "chuck"
     And I fill in "password" with "norris"
     And I press "Create"
    Then I should see "Incorrect input, please revise."
     And I should see "Names must be unique"